services:
  mysql_db:
    image: mariadb:lts-ubi10
    environment:
      MYSQL_ROOT_PASSWORD: SuperSecret2024!
      MYSQL_DATABASE: empresa_db
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: superpassword
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3307:3306"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
